---

## mongodb 管理  inventory/mongodb.ini
- hosts: all
  roles:
  - { role: mongodb, when: action == "install" }


- hosts: all
  tasks:
  - import_role:
      name: mongodb
      tasks_from: uninstall
    when: action == "uninstall"      