---
- block:
    - name: Stop service
      systemd: name=nginx state=stopped enabled=no
      with_items:
        - nginx
        - php-fpm

    - name: Uninstall php
      package: name=php-fpm state=absent

    - name: Remove dircotry
      file: path={{ item }} state=absent
      with_items:
        - /usr/lib/systemd/system/nginx.service
        - /usr/sbin/nginx
        - "{{ middleware_backup }}/nginx.{{ ansible_date_time.date }}.bak"

    - name: Create backup directory
      file: path={{ middleware_backup }} state=directory

    - name: Backup nginx
      shell: |
        \mv /usr/sbin/nginx /usr/sbin/nginx.bak
        \mv {{ middleware_path }}/nginx {{ middleware_backup }}/nginx.{{ ansible_date_time.date }}.bak

    - name: Reload systemd
      systemd: daemon_reload=yes
  ignore_errors: true
