---
- name: "start kafka"
  service: name=kafka-{{ kafka_port }} state=started
  become: true

- name: "stop kafka"
  service: name=kafka-{{ kafka_port }} state=stopped
  become: true

- name: "restart kafka"
  service: name=kafka-{{ kafka_port }} state=restarted
  become: true

