---
- name: Start zookeeper
  service: name=zookeeper-{{zookeeper_client_port}} state=restarted

- name: wait for zookeeper port
  wait_for: port={{zookeeper_client_port}} state=started timeout={{ monasca_wait_for_period }}
